# Generated by Django 5.2a1 on 2025-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.AlterModelOptions(
            name='classsubjectteacher',
            options={'ordering': ['academic_year', 'class_obj']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['academic_year', 'date_conducted']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['exam__academic_year', 'subject']},
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectteacher',
            unique_together={('class_obj', 'subject', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$lcCzwecZwvwaP1O3b4OXck$WlFJrffH5cFso/ONoUUsFXcisdTlV1JHCaBRC0c/+ho=', max_length=128),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Art', 'Art'), ('Science', 'Science'), ('History', 'History'), ('Music', 'Music'), ('Geography', 'Geography'), ('P.E', 'P.E (Physical Education)'), ('Drama', 'Drama'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('I.T', 'I.T (Information Technology)'), ('Foreign Languages', 'Foreign Languages'), ('Social Studies', 'Social Studies'), ('Technology', 'Technology'), ('Philosophy', 'Philosophy'), ('Graphic Design', 'Graphic Design'), ('Literature', 'Literature'), ('Algebra', 'Algebra'), ('Geometry', 'Geometry')], max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='classsubjectteacher',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
