# Generated by Django 5.2a1 on 2025-04-11 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_exam_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$mytYCxRHCQe35BPGrzCr5t$wBNcgxHJJK8SfP7gzUUv+XL6wpu8E45+K49DkSv5HcM=', max_length=128),
        ),
    ]
