# Generated by Django 5.2a1 on 2025-04-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_person_password_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='django123', max_length=128),
        ),
    ]
