# Generated by Django 5.1.5 on 2025-03-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='office.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.subject')),
            ],
            options={
                'unique_together': {('class_model', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='office.person')),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('guardian_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='office.person')),
                ('qualification', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.classsubject')),
                ('student', models.ForeignKey(limit_choices_to={'role__role_name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to='office.person')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_percentage', models.FloatField()),
                ('overall_grade', models.CharField(max_length=5)),
                ('remarks', models.TextField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.academicyear')),
                ('student', models.ForeignKey(limit_choices_to={'role__role_name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to='office.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.role'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.academicyear')),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.class')),
                ('student', models.ForeignKey(limit_choices_to={'role__role_name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to='office.person')),
            ],
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='office.person')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='office.person')),
            ],
            options={
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
