# Generated by Django 5.1.5 on 2025-03-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='year',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.academicyear'),
        ),
        migrations.AddField(
            model_name='grade',
            name='max_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='reportcardsnapshot',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to='office.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='reportcardsnapshot',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to='office.person'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to='office.person'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_model', 'subject', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'class_model', 'academic_year')},
        ),
        migrations.CreateModel(
            name='ParentStudentAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='office.person')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='office.person')),
            ],
            options={
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='ParentStudent',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
